"""Independent calibration of the global Threshold-MM tau.

Calibration seeds: 101, 102, 103 (DISJOINT from the test seeds 42-46), all three bridges,
48 templates per seed, generated by the SAME faithful pipeline functions as the frozen run
(build_semi_synthetic_from_flow_labels + write_synthetic_subgraph_segment_csvs +
flows_from_segment_export_csv + build_cost_matrix_decomposed with the frozen parameters).

Procedure (pre-registered):
  1. Pool all cost cells C_eff across the calibration instances -> empirical cost ECDF.
  2. Threshold grid tau in {0.05, 0.10, ..., 0.95}; cutoff(tau) = tau-quantile of the ECDF
     (equivalent to normalized_cost(i,j) = ECDF(C_ij) <= tau).
  3. For each tau, run Threshold-MM on every calibration instance and compute the pooled
     edge F1 (truth = split + merge + decoy positive edges; see CAPABILITY_DEFINITIONS.md).
  4. Select tau* = argmax pooled edge F1; tie-break: higher pooled precision, then lower tau.
  5. Save calibration/threshold_grid.csv + calibration/selected_threshold.json.
     Per-bridge tau* is recorded as SUPPLEMENTARY; the main baseline uses the GLOBAL tau*.

The test seeds 42-46 are not read by this script.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
sys.path.insert(0, str(REPO / "scripts" / "multi_bridge"))

from baseline_mechanism.common import (  # noqa: E402
    BRIDGES, CALIB_SEEDS, FROZEN, FROZEN_PARAMS, STUDY, N_TEMPLATES,
    evaluate_method, tpl_maps, truth_structure,
)
from cross.domain.evaluation.semi_synthetic_flows import build_semi_synthetic_from_flow_labels  # noqa: E402
from cross.domain.evaluation.synthetic_segment_subgraph import write_synthetic_subgraph_segment_csvs  # noqa: E402
from cross.domain.labels.uot_flow_loader import flows_from_segment_export_csv  # noqa: E402
from cross.domain.uot.cost_matrix import build_cost_matrix_decomposed, default_cost_weights  # noqa: E402
from run_threshold_many_match import TAU_GRID, cutoff_for_tau, ecdf_from_costs, predict_edges  # noqa: E402

OUT = STUDY / "calibration"


def build_calibration_instance(bridge: str, seed: int) -> dict[str, Any]:
    """Generate one calibration instance through the exact frozen generation path."""
    root = OUT / "instances" / bridge / f"seed_{seed}"
    root.mkdir(parents=True, exist_ok=True)
    cost_path = root / "cost.npz"
    if cost_path.is_file():
        c = np.load(cost_path, allow_pickle=False)
        ids = np.load(root / "ids.npz", allow_pickle=True)
        lab = pd.read_csv(root / "labels" / "synthetic_flow_labels.csv", dtype=str, keep_default_na=False)
        sids = [str(x) for x in ids["sids"]]
        tids = [str(x) for x in ids["tids"]]
        tpl_s, tpl_t = tpl_maps(lab, sids, tids)
        return {"root": root, "C": np.asarray(c["C_effective"], dtype=float),
                "sids": sids, "tids": tids, "tpl_s": tpl_s, "tpl_t": tpl_t,
                "truth": truth_structure(lab), "labels": lab,
                "n_cells": int(c["C_effective"].size)}
    pool = FROZEN / "feature_stats" / bridge
    eth_pool = pd.read_csv(pool / "flow_segments_eth.csv", dtype=str, keep_default_na=False)
    bnb_pool = pd.read_csv(pool / "flow_segments_bnb.csv", dtype=str, keep_default_na=False)
    labels = pd.read_csv(pool / "flow_labels.csv", dtype=str, keep_default_na=False)
    labels.to_csv(root / "flow_labels.csv", index=False)
    stats_path = root / "flow_label_stats.json"
    stats_path.write_text(json.dumps({"predominantly_one_to_one": True,
                                      "n_pool_pairs": int(len(labels))}), encoding="utf-8")
    syn_csv, syn_json = build_semi_synthetic_from_flow_labels(
        root / "flow_labels.csv", stats_path, root, seed=seed, max_seeds=N_TEMPLATES, force=True)
    hints = json.loads(syn_json.read_text(encoding="utf-8"))
    clones = hints.get("segment_clone_records") or []
    se = root / "flow_segments_eth_synth.csv"
    sb = root / "flow_segments_bnb_synth.csv"
    write_synthetic_subgraph_segment_csvs(pool / "flow_segments_eth.csv",
                                          pool / "flow_segments_bnb.csv", clones, se, sb)
    eth = flows_from_segment_export_csv(se, chain="ETH")
    bnb = flows_from_segment_export_csv(sb, chain="BNB")
    decomp = build_cost_matrix_decomposed(
        eth, bnb, weights=default_cost_weights(), use_graph=False,
        max_delay_sec=FROZEN_PARAMS["uot_max_delay_sec"],
        causal_violation_penalty=FROZEN_PARAMS["uot_causal_violation_penalty"])
    C = np.maximum(np.asarray(decomp["C"], dtype=float) + np.asarray(decomp["bridge_prior_bonus"], dtype=float), 0.0)
    np.savez(root / "cost.npz", C_effective=C,
             amount_cost=decomp["amount_cost"], time_cost=decomp["time_cost"],
             delay_sec=decomp["delay_sec"])
    sids = [str(f.get("flow_id")) for f in eth]
    tids = [str(f.get("flow_id")) for f in bnb]
    np.savez(root / "ids.npz", sids=np.array(sids, dtype=object), tids=np.array(tids, dtype=object))
    lab = pd.read_csv(root / "labels" / "synthetic_flow_labels.csv", dtype=str, keep_default_na=False) \
        if (root / "labels" / "synthetic_flow_labels.csv").is_file() else pd.read_csv(syn_csv, dtype=str, keep_default_na=False)
    truth = truth_structure(lab)
    tpl_s, tpl_t = tpl_maps(lab, sids, tids)
    return {"root": root, "C": C, "sids": sids, "tids": tids, "tpl_s": tpl_s, "tpl_t": tpl_t,
            "truth": truth, "labels": lab, "n_cells": int(C.size)}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    instances: list[dict[str, Any]] = []
    print("building calibration instances (seeds 101-103, 3 bridges)...", flush=True)
    for bridge in BRIDGES:
        for seed in CALIB_SEEDS:
            inst = build_calibration_instance(bridge, seed)
            instances.append(inst)
            print(f"  {bridge} seed {seed}: grid {inst['C'].shape} "
                  f"cost range [{inst['C'].min():.4f}, {inst['C'].max():.4f}]", flush=True)

    # pooled cost ECDF
    all_costs = np.concatenate([inst["C"].ravel() for inst in instances])
    ecdf = ecdf_from_costs(all_costs)
    np.savez(OUT / "calibration_cost_ecdf.npz", sorted=ecdf["sorted"])
    per_bridge_ecdf = {}
    for bridge in BRIDGES:
        bc = np.concatenate([i["C"].ravel() for i in instances if i["root"].parts[-2] == bridge])
        per_bridge_ecdf[bridge] = ecdf_from_costs(bc)
        np.savez(OUT / f"calibration_cost_ecdf_{bridge}.npz", sorted=per_bridge_ecdf[bridge]["sorted"])

    grid_rows: list[dict[str, Any]] = []
    per_bridge_grid: dict[str, list[dict[str, Any]]] = {b: [] for b in BRIDGES}
    print("evaluating threshold grid...", flush=True)
    for tau in TAU_GRID:
        cutoff = cutoff_for_tau(ecdf, float(tau))
        tp = fp = fn = 0
        split_ex = merge_ex = 0
        n_tpl = 0
        per_bridge_tp = {b: 0 for b in BRIDGES}
        per_bridge_fp = {b: 0 for b in BRIDGES}
        per_bridge_fn = {b: 0 for b in BRIDGES}
        for inst in instances:
            edges = predict_edges(inst["C"], cutoff, inst["sids"], inst["tids"])
            df, summ = evaluate_method(inst, inst["truth"], edges)
            tp += summ["edge_tp_total"]; fp += summ["edge_fp_total"]; fn += summ["edge_fn_total"]
            split_ex += int(df["split_exact"].sum()); merge_ex += int(df["merge_exact"].sum())
            n_tpl += len(df)
            br = inst["root"].parts[-2]
            per_bridge_tp[br] += summ["edge_tp_total"]
            per_bridge_fp[br] += summ["edge_fp_total"]
            per_bridge_fn[br] += summ["edge_fn_total"]
        prec = tp / max(tp + fp, 1)
        rec = tp / max(tp + fn, 1)
        f1 = 2 * prec * rec / max(prec + rec, 1e-12)
        grid_rows.append({
            "tau": tau, "cutoff": cutoff,
            "edge_tp": tp, "edge_fp": fp, "edge_fn": fn,
            "edge_precision": prec, "edge_recall": rec, "edge_f1": f1,
            "split_exact": split_ex / max(n_tpl, 1), "merge_exact": merge_ex / max(n_tpl, 1),
            "n_templates": n_tpl,
        })
        for br in BRIDGES:
            p = per_bridge_tp[br] / max(per_bridge_tp[br] + per_bridge_fp[br], 1)
            r = per_bridge_tp[br] / max(per_bridge_tp[br] + per_bridge_fn[br], 1)
            f = 2 * p * r / max(p + r, 1e-12)
            per_bridge_grid[br].append({"tau": tau, "cutoff": cutoff_for_tau(per_bridge_ecdf[br], float(tau)),
                                        "edge_precision": p, "edge_recall": r, "edge_f1": f})
    grid = pd.DataFrame(grid_rows)
    grid.to_csv(OUT / "threshold_grid.csv", index=False)
    pb_df = pd.concat({b: pd.DataFrame(rows) for b, rows in per_bridge_grid.items()}, names=["bridge"]).reset_index()
    pb_df.to_csv(OUT / "per_bridge_threshold_grid.csv", index=False)

    # selection: pooled edge F1, tie-break precision, then lower tau
    best_idx = grid.sort_values(["edge_f1", "edge_precision", "tau"],
                                ascending=[False, False, True]).iloc[0]
    tau_star = float(best_idx["tau"])
    cutoff_star = float(best_idx["cutoff"])
    per_bridge_best = {}
    for br, rows in per_bridge_grid.items():
        b = sorted(rows, key=lambda r: (-r["edge_f1"], -r["edge_precision"], r["tau"]))[0]
        per_bridge_best[br] = {"tau": b["tau"], "cutoff": b["cutoff"], "edge_f1": b["edge_f1"]}
    selected = {
        "criterion": "pooled edge F1 over calibration templates (truth = split + merge + decoy positive edges)",
        "calibration_seeds": list(CALIB_SEEDS),
        "test_seeds_untouched": list((42, 43, 44, 45, 46)),
        "n_calibration_instances": len(instances),
        "n_templates_total": int(grid.iloc[0]["n_templates"]),
        "n_cost_cells_pooled": int(all_costs.size),
        "global_tau": tau_star,
        "global_cutoff_cost": cutoff_star,
        "ecdf_min": ecdf["min"], "ecdf_max": ecdf["max"],
        "selected_grid_row": best_idx.to_dict(),
        "per_bridge_tau_supplementary": per_bridge_best,
        "rule": "edge kept iff C_ij <= global_cutoff_cost (equivalently ECDF_cal(C_ij) <= global_tau)",
        "threshold_grid_taus": list(TAU_GRID),
    }
    (OUT / "selected_threshold.json").write_text(json.dumps(selected, indent=2, ensure_ascii=False) + "\n",
                                                 encoding="utf-8")
    (OUT / "calibration_instances_meta.json").write_text(json.dumps({
        "instances": [{"bridge": i["root"].parts[-2], "seed": i["root"].parts[-1],
                       "n_src": i["C"].shape[0], "n_tgt": i["C"].shape[1]} for i in instances]},
        indent=2) + "\n", encoding="utf-8")
    print(json.dumps(selected, indent=2))
    print(grid.to_string(index=False, float_format=lambda x: f"{x:.4f}"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
